branch-defaults:
  master:
    environment: ring
  prod:
    environment: ring
global:
  application_name: ring
  default_ec2_keyname: ring-ssh
  default_platform: Node.js
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
